/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nftAuctionSol from "./NftAuction.sol";
export type { nftAuctionSol };
import type * as nftAuctionFactorySol from "./NftAuctionFactory.sol";
export type { nftAuctionFactorySol };
import type * as crosschain from "./crosschain";
export type { crosschain };
import type * as mocks from "./mocks";
export type { mocks };
export type { MyNFT } from "./MyNFT";
export type { NftAuctionV2 } from "./NftAuctionV2";
export type { PriceOracle } from "./PriceOracle";
