/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAuctionBid,
  IAuctionBidInterface,
} from "../../../../contracts/crosschain/CrossChainGateway.sol/IAuctionBid";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "bidERC20",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "bidETH",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IAuctionBid__factory {
  static readonly abi = _abi;
  static createInterface(): IAuctionBidInterface {
    return new Interface(_abi) as IAuctionBidInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IAuctionBid {
    return new Contract(address, _abi, runner) as unknown as IAuctionBid;
  }
}
