/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAuction,
  IAuctionInterface,
} from "../../../contracts/NftAuctionFactory.sol/IAuction";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "factory_",
        type: "address",
      },
      {
        internalType: "address",
        name: "seller_",
        type: "address",
      },
      {
        internalType: "address",
        name: "nft_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId_",
        type: "uint256",
      },
      {
        internalType: "uint64",
        name: "startTime_",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "endTime_",
        type: "uint64",
      },
      {
        internalType: "uint256",
        name: "startPriceUsd_",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "oracle_",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAuction__factory {
  static readonly abi = _abi;
  static createInterface(): IAuctionInterface {
    return new Interface(_abi) as IAuctionInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IAuction {
    return new Contract(address, _abi, runner) as unknown as IAuction;
  }
}
