/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFactoryView,
  IFactoryViewInterface,
} from "../../../contracts/NftAuction.sol/IFactoryView";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "feeBpsFor",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "feeTo",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IFactoryView__factory {
  static readonly abi = _abi;
  static createInterface(): IFactoryViewInterface {
    return new Interface(_abi) as IFactoryViewInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFactoryView {
    return new Contract(address, _abi, runner) as unknown as IFactoryView;
  }
}
