/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as nftAuctionSol from "./NftAuction.sol";
export * as nftAuctionFactorySol from "./NftAuctionFactory.sol";
export * as crosschain from "./crosschain";
export * as mocks from "./mocks";
export { MyNFT__factory } from "./MyNFT__factory";
export { NftAuctionV2__factory } from "./NftAuctionV2__factory";
export { PriceOracle__factory } from "./PriceOracle__factory";
